name = "trading-app"
main = ".open-next/worker.js"
workers_dev = false
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "trading-app"

[[routes]]
pattern = "traderrecord.uk"
zone_name = "traderrecord.uk"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "trading-app-db"
database_id = "b622591d-de94-46f6-9128-53fc17d567ac"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "trading-app-images"
