name = "trading-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "trading-app-db"
database_id = "b622591d-de94-46f6-9128-53fc17d567ac" # Placeholder for local dev
migrations_dir = "drizzle"
